import { CommunityMember, MemberAnalytics, MemberStatus } from "@/types/member";
import { UserRole } from "@/types/role";

export const INITIAL_MEMBERS: CommunityMember[] = [
    {
        id: "mem_1",
        name: "Alex Silva",
        email: "alex.silva@solarlink.org",
        role: "solar_owner",
        status: "active",
        solarCapacityKw: 8.5,
        joinedAt: "Jan 15, 2024",
        phone: "+1 (555) 234-5678",
    },
    {
        id: "mem_2",
        name: "Marcus Vance",
        email: "marcus.vance@solarlink.org",
        role: "manager",
        status: "active",
        joinedAt: "Oct 10, 2023",
        phone: "+1 (555) 345-6789",
    },
    {
        id: "mem_3",
        name: "Elena Rostova",
        email: "elena.r@solarlink.org",
        role: "household",
        status: "active",
        monthlyAllocationKwh: 45,
        joinedAt: "Feb 20, 2024",
        phone: "+1 (555) 456-7890",
    },
    {
        id: "mem_4",
        name: "David Chen",
        email: "david.c@solarlink.org",
        role: "technician",
        status: "active",
        assignedGrid: "Sector 4B Substation",
        joinedAt: "Dec 01, 2023",
        phone: "+1 (555) 567-8901",
    },
    {
        id: "mem_5",
        name: "Sophia Martinez",
        email: "sophia.m@solarlink.org",
        role: "solar_owner",
        status: "active",
        solarCapacityKw: 12.0,
        joinedAt: "Mar 05, 2024",
        phone: "+1 (555) 678-9012",
    },
    {
        id: "mem_6",
        name: "Liam O'Connor",
        email: "liam.oc@solarlink.org",
        role: "household",
        status: "active",
        monthlyAllocationKwh: 35,
        joinedAt: "Apr 12, 2024",
        phone: "+1 (555) 789-0123",
    },
    {
        id: "mem_7",
        name: "Amara Johnson",
        email: "amara.j@solarlink.org",
        role: "household",
        status: "pending",
        monthlyAllocationKwh: 30,
        joinedAt: "2 days ago",
        phone: "+1 (555) 890-1234",
    },
    {
        id: "mem_8",
        name: "Kenji Sato",
        email: "kenji.sato@solarlink.org",
        role: "solar_owner",
        status: "pending",
        solarCapacityKw: 6.4,
        joinedAt: "1 day ago",
        phone: "+1 (555) 901-2345",
    },
    {
        id: "mem_9",
        name: "Rachel Green",
        email: "rachel.g@solarlink.org",
        role: "technician",
        status: "active",
        assignedGrid: "North Residential Grid",
        joinedAt: "Nov 18, 2023",
        phone: "+1 (555) 012-3456",
    },
];

export function calculateMemberAnalytics(members: CommunityMember[]): MemberAnalytics {
    return {
        totalMembers: members.length,
        activeMembers: members.filter((m) => m.status === "active").length,
        pendingMembers: members.filter((m) => m.status === "pending").length,
        householdCount: members.filter((m) => m.role === "household").length,
        solarOwnerCount: members.filter((m) => m.role === "solar_owner").length,
        technicianCount: members.filter((m) => m.role === "technician").length,
        managerCount: members.filter((m) => m.role === "manager").length,
    };
}
